# Generated by Django 4.2.4 on 2023-09-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=None, upload_to='room/'),
        ),
    ]
