# Generated by Django 4.2.4 on 2023-09-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_rename_customer_email_reservation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
