# Generated by Django 4.2.4 on 2023-09-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aminities',
            fields=[
                ('aminities_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titles', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
            ],
        ),
    ]
